CREATE DATABASE school_db;
USE school_db;

CREATE TABLE Class(
	ID INT AUTO_INCREMENT NOT NULL,
	Classroom VARCHAR(255) NOT NULL,
	Teacher_ID INT NOT NULL,
    Student_ID INT NOT NULL,
	
    PRIMARY KEY (ID)
);

CREATE TABLE Teachers(
	ID INT AUTO_INCREMENT NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
    Student_ID INT NOT NULL,
	Parent_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Students (
	ID INT AUTO_INCREMENT NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
    Teacher_ID INT NOT NULL,
	Parent_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Parents (
	ID INT AUTO_INCREMENT NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
    Student_ID INT NOT NULL,
    Teacher_ID INT NOT NULL,
	PRIMARY KEY (ID)
);