<<<<<<< HEAD
CREATE DATABASE users_db;
USE users_db;

CREATE TABLE Teachers(
	ID INT AUTO_INCREMENT NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
    Student_ID INT NOT NULL,
	Parent_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Students (
	ID INT AUTO_INCREMENT NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
    Teacher_ID INT NOT NULL,
	Parent_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Parents (
	ID INT AUTO_INCREMENT NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
    Student_ID INT NOT NULL,
    Teacher_ID INT NOT NULL,
	PRIMARY KEY (ID)
);
=======
schema.sql
>>>>>>> 236eec02cb27ed4e7d4fd64e02d579c8a7296c34
